package InicioMvc;

import mediador.IComponente;
import mediador.IMediador;
import observers.IObserver;

public class InicioView extends javax.swing.JFrame implements IComponente {

    private final InicioModel inicioModel;
    private IMediador mediador;
    private IObserver observerCrearPartida;
    private IObserver observerUnirsePartida;

    /**
     * Creates new form InicioView
     *
     * @param inicioModel
     */
    public InicioView(InicioModel inicioModel) {
        initComponents();
        this.inicioModel = inicioModel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnUnirse = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crearPartida.png"))); // NOI18N
        btnCrear.setToolTipText("");
        btnCrear.setBorderPainted(false);
        btnCrear.setContentAreaFilled(false);
        btnCrear.setFocusPainted(false);
        btnCrear.setFocusable(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 270, 70));

        btnUnirse.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unirseApartida.png"))); // NOI18N
        btnUnirse.setToolTipText("");
        btnUnirse.setBorderPainted(false);
        btnUnirse.setContentAreaFilled(false);
        btnUnirse.setFocusPainted(false);
        btnUnirse.setFocusable(false);
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });
        jPanel1.add(btnUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 210, 70));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Inicio.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        ejecutarAccionCrearPartida();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
        ejecutarAccionUnirseAPartida();
    }//GEN-LAST:event_btnUnirseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnUnirse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables

    public void agregarIEventoCrearPartida(IObserver listener) {
        this.observerCrearPartida = listener;
    }

    public void ejecutarAccionCrearPartida() {
        if (observerCrearPartida != null) {
            observerCrearPartida.actualizar();
        }
    }

    public void agregarIEventoUnirseAPartida(IObserver listener) {
        this.observerUnirsePartida = listener;
    }

    public void ejecutarAccionUnirseAPartida() {
        if (observerUnirsePartida != null) {
            observerUnirsePartida.actualizar();
        }
    }
    
    @Override
    public void setMediador(IMediador mediador) {
        this.mediador = mediador;
    }

}
