/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unirseAPartida;

import eventos.JugadorUnirseAPartidaDto;
import eventos.NodoDto;
import javax.swing.JOptionPane;
import mediador.IComponente;
import mediador.IMediador;
import observers.IEventoAgregarJugadorAPartida;
import observers.IObserver;

/**
 *
 * @author tacot
 */
public class UnirseAPartidaView extends javax.swing.JFrame implements IComponente {

     private IMediador mediador;
     private final UnirseAPartidaModel partidaModel;
     private IEventoAgregarJugadorAPartida observerUnirseAPartida;
     private IObserver observerRegresar;

     /**
      * Creates new form UnirseAPartidaView
      */
     public UnirseAPartidaView(UnirseAPartidaModel partidaModel) {
          initComponents();
          this.partidaModel = partidaModel;
          partidaModel.agregarIEventoNombreInvalido(new accionNombreInvalido());
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel4 = new javax.swing.JLabel();
          jComboBox1 = new javax.swing.JComboBox<>();
          jPanel1 = new javax.swing.JPanel();
          btnUnirseAPartida = new javax.swing.JButton();
          jLabel2 = new javax.swing.JLabel();
          txtNombre = new javax.swing.JTextField();
          txtCodigoPartida = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          btnRegresar = new javax.swing.JButton();
          jLabel5 = new javax.swing.JLabel();
          cbxAvatar = new javax.swing.JComboBox<>();
          jLabel1 = new javax.swing.JLabel();

          jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selecciona avatar.png"))); // NOI18N

          jComboBox1.setBackground(new java.awt.Color(174, 70, 43));
          jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avatar 1", "Avatar 2", "Avatar 3. Avatar 4" }));
          jComboBox1.setBorder(null);
          jComboBox1.setFocusable(false);

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          btnUnirseAPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unirseApartida.png"))); // NOI18N
          btnUnirseAPartida.setBorder(null);
          btnUnirseAPartida.setContentAreaFilled(false);
          btnUnirseAPartida.setFocusPainted(false);
          btnUnirseAPartida.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnUnirseAPartidaActionPerformed(evt);
               }
          });
          jPanel1.add(btnUnirseAPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

          jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ingreseNombre.png"))); // NOI18N
          jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

          txtNombre.setBackground(new java.awt.Color(174, 70, 43));
          txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
          txtNombre.setForeground(new java.awt.Color(255, 255, 255));
          txtNombre.setToolTipText("Nombre del jugador");
          txtNombre.setBorder(null);
          jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 190, -1));

          txtCodigoPartida.setBackground(new java.awt.Color(174, 70, 43));
          txtCodigoPartida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
          txtCodigoPartida.setForeground(new java.awt.Color(255, 255, 255));
          txtCodigoPartida.setToolTipText("Nombre del jugador");
          txtCodigoPartida.setBorder(null);
          jPanel1.add(txtCodigoPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 190, -1));

          jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigoPartida.png"))); // NOI18N
          jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 190, -1));

          btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
          btnRegresar.setBorder(null);
          btnRegresar.setContentAreaFilled(false);
          btnRegresar.setFocusPainted(false);
          btnRegresar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnRegresarActionPerformed(evt);
               }
          });
          jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 30));

          jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selecciona avatar.png"))); // NOI18N
          jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

          cbxAvatar.setBackground(new java.awt.Color(174, 70, 43));
          cbxAvatar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avatar 1", "Avatar 2", "Avatar 3. Avatar 4" }));
          cbxAvatar.setBorder(null);
          cbxAvatar.setFocusable(false);
          jPanel1.add(cbxAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 190, -1));

          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_UnirseAPartida.jpg"))); // NOI18N
          jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          );

          pack();
          setLocationRelativeTo(null);
     }// </editor-fold>//GEN-END:initComponents


    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

         ejecutarAccionRegresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

     private void btnUnirseAPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseAPartidaActionPerformed

          int avatar = 1 + this.cbxAvatar.getSelectedIndex();
          ejecutarAccionUnirseAPartida(txtNombre.getText(), avatar, txtCodigoPartida.getText());
     }//GEN-LAST:event_btnUnirseAPartidaActionPerformed

     public void validarDatos() {
          JOptionPane.showMessageDialog(null, "No se permiten caracteres especiales(solo '_') ni espacios, el nombre tiene que ser mayor a 3 y menor a 15 caracteres");
     }

     public void agregarIEventoRegresar(IObserver listener) {
          this.observerRegresar = listener;

     }

     public void ejecutarAccionRegresar() {
          if (observerRegresar != null) {
               observerRegresar.actualizar();
          }
     }

     public void agregarIEventoUnirseAPartida(IEventoAgregarJugadorAPartida listener) {
          this.observerUnirseAPartida = listener;
     }

     public void ejecutarAccionUnirseAPartida(String nombre, int avatar, String codigoPartida) {
          if (observerUnirseAPartida != null) {
               JugadorUnirseAPartidaDto jugador = new JugadorUnirseAPartidaDto(new NodoDto(nombre, avatar), codigoPartida);

               observerUnirseAPartida.agregarJugadorAPartida(jugador);
          }
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btnRegresar;
     private javax.swing.JButton btnUnirseAPartida;
     private javax.swing.JComboBox<String> cbxAvatar;
     private javax.swing.JComboBox<String> jComboBox1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JTextField txtCodigoPartida;
     private javax.swing.JTextField txtNombre;
     // End of variables declaration//GEN-END:variables

     @Override
     public void setMediador(IMediador mediador) {
          this.mediador = mediador;
     }

     private class accionNombreInvalido implements IObserver {

          @Override
          public void actualizar() {
               validarDatos();
          }
     }
}
