/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unirseAPartida;

import eventos.JugadorUnirseAPartidaDto;
import eventos.NodoDto;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import mediador.IComponente;
import mediador.IMediador;
import observers.IEventoSeleccion;
import observersLogicaAServidorCentral.IEventoAgregarJugadorAPartida;
import observers.IObserver;

/**
 *
 * @author tacot
 */
public class UnirseAPartidaView extends javax.swing.JFrame implements IComponente {

    private IMediador mediador;
    private final UnirseAPartidaModel partidaModel;
    private IEventoAgregarJugadorAPartida observerUnirseAPartida;
    private IEventoSeleccion observerSeleccionIzquierda;
    private IEventoSeleccion observerSeleccionDerecha;
    private IObserver observerRegresar;
    private int avatar = 0;

    /**
     * Creates new form UnirseAPartidaView
     */
    public UnirseAPartidaView(UnirseAPartidaModel partidaModel) {
        initComponents();
        this.partidaModel = partidaModel;
        partidaModel.agregarIEventoNombreInvalido(new accionNombreInvalido());
        partidaModel.agregarObservadorCambioAvatar(new accionSeleccionAvatar());
        etiquetaAvatar.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnUnirseAPartida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigoPartida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        flechaSeleccionDer = new javax.swing.JButton();
        etiquetaAvatar = new javax.swing.JLabel();
        flechaSeleccionIzq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selecciona avatar.png"))); // NOI18N

        jComboBox1.setBackground(new java.awt.Color(174, 70, 43));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avatar 1", "Avatar 2", "Avatar 3. Avatar 4" }));
        jComboBox1.setBorder(null);
        jComboBox1.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUnirseAPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unirseApartida.png"))); // NOI18N
        btnUnirseAPartida.setBorder(null);
        btnUnirseAPartida.setContentAreaFilled(false);
        btnUnirseAPartida.setFocusPainted(false);
        btnUnirseAPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseAPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnUnirseAPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ingreseNombre.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        txtNombre.setBackground(new java.awt.Color(174, 70, 43));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setToolTipText("Nombre del jugador");
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 190, -1));

        txtCodigoPartida.setBackground(new java.awt.Color(174, 70, 43));
        txtCodigoPartida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCodigoPartida.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoPartida.setToolTipText("Nombre del jugador");
        txtCodigoPartida.setBorder(null);
        jPanel1.add(txtCodigoPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 190, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigoPartida.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 190, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selecciona avatar.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        flechaSeleccionDer.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        flechaSeleccionDer.setForeground(new java.awt.Color(253, 231, 194));
        flechaSeleccionDer.setText(">");
        flechaSeleccionDer.setBorderPainted(false);
        flechaSeleccionDer.setContentAreaFilled(false);
        flechaSeleccionDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flechaSeleccionDerActionPerformed(evt);
            }
        });
        jPanel1.add(flechaSeleccionDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 110, 110));
        jPanel1.add(etiquetaAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 110, 120));

        flechaSeleccionIzq.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        flechaSeleccionIzq.setForeground(new java.awt.Color(255, 231, 202));
        flechaSeleccionIzq.setText("<");
        flechaSeleccionIzq.setBorderPainted(false);
        flechaSeleccionIzq.setContentAreaFilled(false);
        flechaSeleccionIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flechaSeleccionIzqActionPerformed(evt);
            }
        });
        jPanel1.add(flechaSeleccionIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 110, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_UnirseAPartida.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        ejecutarAccionRegresar();
    }//GEN-LAST:event_btnRegresarActionPerformed

     private void btnUnirseAPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseAPartidaActionPerformed
         Icon icono = etiquetaAvatar.getIcon();
         icono.toString();
         if (icono instanceof ImageIcon imageIcon) {
             String descripcion = imageIcon.getDescription();

             if (descripcion.contains("avatar1.png")) {
                 avatar = 1;
             } else if (descripcion.contains("avatar2.png")) {
                 avatar = 2;
             } else if (descripcion.contains("avatar3.png")) {
                 avatar = 3;
             } else if (descripcion.contains("avatar4.png")) {
                 avatar = 4;
             }
         }
         ejecutarAccionUnirseAPartida(txtNombre.getText(), avatar, txtCodigoPartida.getText());
         txtNombre.setText("");
         txtCodigoPartida.setText("");
         actualizarAvatar();
     }//GEN-LAST:event_btnUnirseAPartidaActionPerformed

    private void flechaSeleccionDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flechaSeleccionDerActionPerformed
        ejecutarAccionSeleccionDerecha();
    }//GEN-LAST:event_flechaSeleccionDerActionPerformed

    private void flechaSeleccionIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flechaSeleccionIzqActionPerformed
        ejecutarAccionSeleccionIzquierda();
    }//GEN-LAST:event_flechaSeleccionIzqActionPerformed

    public void validarDatos() {
        JOptionPane.showMessageDialog(null, "No se permiten caracteres especiales(solo '_') ni espacios, el nombre tiene que ser mayor a 3 y menor a 15 caracteres");
    }

    public void agregarIEventoRegresar(IObserver listener) {
        this.observerRegresar = listener;

    }

    public void ejecutarAccionRegresar() {
        if (observerRegresar != null) {
            observerRegresar.actualizar();
        }
    }

    public void agregarIEventoUnirseAPartida(IEventoAgregarJugadorAPartida listener) {
        this.observerUnirseAPartida = listener;
    }

    public void ejecutarAccionUnirseAPartida(String nombre, int avatar, String codigoPartida) {
        if (observerUnirseAPartida != null) {
            JugadorUnirseAPartidaDto jugador = new JugadorUnirseAPartidaDto(new NodoDto(), codigoPartida, nombre, avatar);

            observerUnirseAPartida.agregarJugadorAPartida(jugador);
        }
    }

    public void agregarIEventoSeleccionIzquierda(IEventoSeleccion listener) {
        this.observerSeleccionIzquierda = listener;
    }

    public void agregarIEventoSeleccionDerecha(IEventoSeleccion listener) {
        this.observerSeleccionDerecha = listener;
    }

    public void ejecutarAccionSeleccionIzquierda() {
        if (observerSeleccionIzquierda != null) {
            observerSeleccionIzquierda.actualizarAvatar();
        }
    }

    public void ejecutarAccionSeleccionDerecha() {
        if (observerSeleccionDerecha != null) {
            observerSeleccionDerecha.actualizarAvatar();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnUnirseAPartida;
    private javax.swing.JLabel etiquetaAvatar;
    private javax.swing.JButton flechaSeleccionDer;
    private javax.swing.JButton flechaSeleccionIzq;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigoPartida;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setMediador(IMediador mediador) {
        this.mediador = mediador;
    }

    private class accionNombreInvalido implements IObserver {

        @Override
        public void actualizar() {
            validarDatos();
        }
    }

    private class accionSeleccionAvatar implements IObserver {

        @Override
        public void actualizar() {
            actualizarAvatar();
        }
    }

    public void actualizarAvatar() {
        etiquetaAvatar.setIcon(cargarIconoAvatar(partidaModel.getRutaAvatarActual()));
    }

    private ImageIcon cargarIconoAvatar(String ruta) {
        java.net.URL imgURL = getClass().getResource(ruta);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("No se pudo encontrar el archivo: " + ruta);
            return null;
        }
    }
}
