/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TableroMvc;

import dtos.FichaDto;
import dtos.JugadorDto;
import eventos.JugadorAEliminarDto;
import eventos.PasarTurno;
import eventos.PonerFichaDto;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import mediador.IComponente;
import mediador.IMediador;
import observers.IEventoPasarTurno;
import observers.IEventoPonerFicha;
import observers.IEventoSalirDePartida;
import observers.IEventoTomarFichaDelPozo;
import observers.IObserver;

public class TableroView extends javax.swing.JFrame implements IComponente {

     private IMediador mediador;

     private final TableroModel tableroModel;

     private IEventoPonerFicha observerPonerFicha;
     private IEventoTomarFichaDelPozo observerTomarDelPozo;
     private IEventoPasarTurno observerPasarTurno;
     private IEventoSalirDePartida observerSalirDePartida;
     private TableroPanel tableroPanel;

     /**
      * Creates new form TableroView
      *
      * @param tableroModel
      */
     public TableroView(TableroModel tableroModel) {
          initComponents();
          this.tableroModel = tableroModel;
         tableroPanel = new TableroPanel(tableroModel);
        add(tableroPanel, BorderLayout.CENTER);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pozo = new javax.swing.JPanel();
        pozo = new javax.swing.JButton();
        Jugador4 = new javax.swing.JPanel();
        Jugador3 = new javax.swing.JPanel();
        Jugador2 = new javax.swing.JPanel();
        Jugador1 = new javax.swing.JPanel();
        avatar1 = new javax.swing.JLabel();
        avatar2 = new javax.swing.JLabel();
        avatar3 = new javax.swing.JLabel();
        avatar4 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pozo.setBackground(new java.awt.Color(255, 255, 255));

        pozo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pozo.png"))); // NOI18N
        pozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pozoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PozoLayout = new javax.swing.GroupLayout(Pozo);
        Pozo.setLayout(PozoLayout);
        PozoLayout.setHorizontalGroup(
            PozoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PozoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pozo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PozoLayout.setVerticalGroup(
            PozoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PozoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pozo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(Pozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 130, 120));

        Jugador4.setBackground(new java.awt.Color(255, 255, 255));
        Jugador4.setEnabled(false);

        javax.swing.GroupLayout Jugador4Layout = new javax.swing.GroupLayout(Jugador4);
        Jugador4.setLayout(Jugador4Layout);
        Jugador4Layout.setHorizontalGroup(
            Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Jugador4Layout.setVerticalGroup(
            Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(Jugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, 50, 240));

        Jugador3.setBackground(new java.awt.Color(255, 255, 255));
        Jugador3.setEnabled(false);

        javax.swing.GroupLayout Jugador3Layout = new javax.swing.GroupLayout(Jugador3);
        Jugador3.setLayout(Jugador3Layout);
        Jugador3Layout.setHorizontalGroup(
            Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        Jugador3Layout.setVerticalGroup(
            Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(Jugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 450, 50));

        Jugador2.setBackground(new java.awt.Color(255, 255, 255));
        Jugador2.setEnabled(false);

        javax.swing.GroupLayout Jugador2Layout = new javax.swing.GroupLayout(Jugador2);
        Jugador2.setLayout(Jugador2Layout);
        Jugador2Layout.setHorizontalGroup(
            Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Jugador2Layout.setVerticalGroup(
            Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(Jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 50, 240));

        Jugador1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Jugador1Layout = new javax.swing.GroupLayout(Jugador1);
        Jugador1.setLayout(Jugador1Layout);
        Jugador1Layout.setHorizontalGroup(
            Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        Jugador1Layout.setVerticalGroup(
            Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(Jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 740, 120));
        getContentPane().add(avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 80, 100));

        avatar2.setEnabled(false);
        getContentPane().add(avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, 100));

        avatar3.setEnabled(false);
        getContentPane().add(avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 80, 100));

        avatar4.setEnabled(false);
        getContentPane().add(avatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 120, 80, 100));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenFondo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pozoActionPerformed
//    ejecutarEventoTomarFichaDelPozo();
    }//GEN-LAST:event_pozoActionPerformed

     public void agregarIEventoPonerFicha(IEventoPonerFicha listener) {
          this.observerPonerFicha = listener;
     }

     public void ejecutarEventoPonerFicha(PonerFichaDto ficha) {
          if (observerPonerFicha != null) {
               observerPonerFicha.ponerFicha(ficha);
          }
     }

     public void agregarEventoTomarFichaDelPozo(IEventoTomarFichaDelPozo listener) {
          this.observerTomarDelPozo = listener;
     }

     public void ejecutarEventoTomarFichaDelPozo(FichaDto fichaSacada) {
          if (observerTomarDelPozo != null) {
               observerTomarDelPozo.tomarFichaDelPozo(fichaSacada);
          }
     }

     public void agregarEventoPasarTurno(IEventoPasarTurno listener) {
          this.observerPasarTurno = listener;
     }

     public void ejecutarEventoPasarTurno(PasarTurno pasarTurno) {
          if (observerPasarTurno != null) {
               observerPasarTurno.pasarTurno(pasarTurno);
          }
     }

     public void agregarEventoSalirDePartida(IEventoSalirDePartida listener) {
          this.observerSalirDePartida = listener;
     }

     public void ejecutarEventoSalirDePartida(JugadorAEliminarDto jugador) {
          if (observerSalirDePartida != null) {
               observerSalirDePartida.salirDePartida(jugador);
          }
     }
     public class TableroPanel extends JPanel {
        private final int[][] tablero;

        public TableroPanel(TableroModel array) {
            this.tablero = array.traerArreglo();
            setPreferredSize(new Dimension(800, 800));
        }
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jugador1;
    private javax.swing.JPanel Jugador2;
    private javax.swing.JPanel Jugador3;
    private javax.swing.JPanel Jugador4;
    private javax.swing.JPanel Pozo;
    private javax.swing.JLabel avatar1;
    private javax.swing.JLabel avatar2;
    private javax.swing.JLabel avatar3;
    private javax.swing.JLabel avatar4;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton pozo;
    // End of variables declaration//GEN-END:variables
  
    
     @Override
     public void setMediador(IMediador mediador) {
          this.mediador = mediador;
     }

}
