package crearMesa;

import java.util.ArrayList;
import java.util.List;
import mediador.IComponente;
import mediador.IMediador;
import observers.IObserver;

/**
 *
 * @author tacot
 */
public class CrearMesaView extends javax.swing.JFrame implements IComponente{

        private List<IObserver> observadores = new ArrayList<>();
        private CrearMesaModel model;
        private IMediador mediador;
        

    /**
     * Creates new form CrearMesa
     * @param modelo
     */
    public CrearMesaView(CrearMesaModel modelo) {
        initComponents();
        model = modelo;
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cantidadFichas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelFondo2 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Numero de fichas a jugar");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, 30));

        cantidadFichas.setBackground(new java.awt.Color(242, 242, 242));
        cantidadFichas.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        cantidadFichas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7" }));
        jPanel2.add(cantidadFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crearMesa.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 150, 30));

        labelFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuadrado azul.jpg"))); // NOI18N
        jPanel2.add(labelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 400));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 480, 400));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nWFiIuU.jpg"))); // NOI18N
        jPanel1.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cantidadFichas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelFondo2;
    // End of variables declaration//GEN-END:variables


    @Override
    public void setMediador(IMediador mediador) {
    }
}
